import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ChakraProvider } from "@chakra-ui/react";
import Section from "../components/section";
import Header from "../components/header";
import supabase from "../../utils/supabase";
import { useEffect, useState } from "react";
import { userState } from "@/store/auth";
import { useRecoilState } from "recoil";

const inter = Inter({ subsets: ["latin"] });

type User = {
  id: number;
  created_at: Date;
  name: string;
  email: string;
  password: string;
};

type SectionType = {
  id: number;
  created_at: string;
  name: string;
};

export default function Home() {
  const [user, setUser] = useRecoilState(userState);
  const [sectionData, setSectionData] = useState<SectionType[]>();
  useEffect(() => {
    const fetchUser = async () => {
      const { data: result, error } = await supabase
        .from("users")
        .select()
        .eq("id", 1)
        .limit(1)
        .single();
      console.log(result);
      const userData = result as User;
      if (!error) {
        setUser(userData);
      }
      const { data: section, error: sectionError } = await supabase.from("section").select();
      console.log(section);
      const sections = section as SectionType[];
      if (!error) {
        setSectionData(sections);
      }
    };
    fetchUser();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {sectionData?.map((section) => (
        <Section
          name={section.name}
          id={section.id}
          created_ad={section.created_at}
          key={section.id}
        />
      ))}
    </>
  );
}
