import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ChakraProvider } from "@chakra-ui/react";
import Sections from "../components/sections";
import Header from "../components/header";
import supabase from "../../utils/supabase";
import { useEffect } from "react";
import { userState } from "@/store/auth";
import { useRecoilState } from "recoil";

const inter = Inter({ subsets: ["latin"] });

type User = {
  id: number;
  created_at: Date;
  name: string;
  email: string;
  password: string;
};

export default function Home() {
  const [user, setUser] = useRecoilState(userState);
  useEffect(() => {
    const fetchUser = async () => {
      const { data: result, error } = await supabase
        .from("users")
        .select()
        .eq("id", 1)
        .limit(1)
        .single();
      console.log(result);
      const userData = result as User;
      if (!error) {
        setUser(userData);
      }
    };
    fetchUser();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sections />
      <Sections />
      <Sections />
    </>
  );
}
